server:
  port: 8081
spring:
  application:
    name: movie-rank
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/mydatabase
    username: myuser
    password: secret
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-app-client
            client-secret: spring-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/demo-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/demo-realm
