spring:
  application:
    name: movie-rank
  docker:
    compose:
      enabled: true
      file: docker-compose.yml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/mydatabase
    username: myuser
    password: secret
  cache:
    cache-names: movies


resilience4j:
  ratelimiter:
    instances:
      rateMovie:
        limit-for-period: 3
        limit-refresh-period: 10s
        timeout-duration: 0s